CREATE ROLE readonly PASSWORD 'Senhaboa123!';
GRANT CONNECT ON DATABASE thiago_sistema_hospitalar_bd TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;
CREATE ROLE professor WITH LOGIN PASSWORD 'Senhaboa456!';
GRANT readonly TO professor;
